### ISSUE TITLE
Syntax error at '}' reported on Puppet v4.4.0

### ISSUE THREAD

**Issue by gothicx** [Yuav/puppet-autofs#12]
Hi,

I'm currently using the latest version with Puppet v4.4.0

Error: Could not parse for environment XXX: Syntax error at '}' at /etc/puppetlabs/code/environments/LAN/modules/autofs/vendor/bundle/ruby/2.1.0/gems/puppet-4.3.2/spec/fixtures/unit/parser/functions/create_resources/foo/manifests/wrongdefine.pp:3:1 on node xxx

**Comment by Yuav** [comment]
According do your output, you're using puppet-4.3.2 ?

I just tried 4.4.0 and 4.3.2 now, on the master branch - and I'm unable to reproduce it.

My steps:

    export PUPPET_GEM_VERSION=4.3.2
    bundle update
    bundle exec rake test

and

    export PUPPET_GEM_VERSION=4.3.2
    bundle update
    bundle exec rake test

In any case, I'm pushing a new release now - 1.2.0. This is the version I used to run the above tests. Please verify!
