### ISSUE TITLE
How to specify --timeout?

### ISSUE THREAD

**Issue by felipe1982** [Yuav/puppet-autofs#13]
How would I be able to specify a `--timeout`?

**Comment by Yuav** [comment]
What's an example of how you would use this normally?

**Comment by felipe1982** [comment]
```
# /etc/auto.master
# timeout : automatically unmount mounts when not used for X seconds
/misc /etc/auto.misc --timeout=300
```

**Comment by Yuav** [comment]
This is counter intuitive currently, as the options for the auto.master file is only exposed in the mountentry resource

You would have to define a mount entry prior to the actual mount, to include additional options

```
mount_entries => {
    '/etc/auto._misc' => { # Resource name match generated name in Mount['misc']
        mountpoint => '/misc',
        mountfile => '/etc/auto._misc', # Matched to auto generated name in Mount['misc']
        options => '--timeout=300',
    }
},
mounts => {
    'misc' => {
        remote => 'nfs:/export/misc/stuff',
        mountpoint => '/misc/stuff',
    }
}
```

The above example has been added to README.md as well

I did however find a bug with this approach, which I've patched and verified with spec tests for version 1.2.1
