### ISSUE TITLE
Mount different things over the same mapfile

### ISSUE THREAD

**Issue by ceso** [Yuav/puppet-autofs#2]
Hi!

I'm using your puppet class with foreman, i'm having a problem. I can't set two mounts for the same mapfile, example:

/etc/auto.master content:

/- /etc/auto.example.com

/etc/auto.example.com content:

/example -fstype=cifs,rw ://example01.com/example
/example2 -fstype=cifs,rw ://example01.com/examplee

Now, i can't do that with foreman and neither from puppet in cli.

I think the options maybe is "mount_files", but you in the comments put " A hash of files to populate and include in auto.master", or could config_file, but thats other parameter.

Can you guide me and explain me, how i should do this that? Or is a feature that your class dosen't have?

Regards!
Leandro.

**Comment by Yuav** [comment]
This is supported. You simply add another entry in the hashmap argument.

The Foreman uses hiera for supplying parameters, so the input is the same as before (hash value), but the syntax is slightly different. I've also updated the README.md to show multiple entries in the hashmap

**Comment by ceso** [comment]
Not working, I did the thing you told me, but is not working yet.
I put the config in type yaml, foreman accept syntax, but if I put in hash, not import the way I worte, they say thats wrong.

And when I wrote two entrys on foreman in mounts, he delete me one of they, for example, if I type within mounts:

'myexample.com':
  remote: 'nfs:/example01.com/example'
  mountpoint: '/remote/server01
  options: 'soft, ro'

'myexample.com':
  remote: 'nfs:/example01.com/example2'
  mountpoint: '/remote/server/010'
  options: 'hard, rw'

or even:

'myexample.com':
  remote: 'nfs:/example01.com/example2'
  mountpoint: '/remote/server/010'
  options: 'hard, rw'

'examples.org':
  remote: 'nfs:/server.example.com/test'
  mountpoint: '/server/remote/examples'
  options: 'hard, rw'

Always foreman delete one of the entrys, even if they are correct.

Do you have idea why this not work? If i did commit a mistake, can you correct me? Or give me a example that works for you in foreman?

Thanks a lot!
And if you can't understand something, please talk me, english isn't my native language.

Regards!
Leandro.
