### ISSUE TITLE
Puppet style error

### ISSUE THREAD

**Issue by aairey** [Yuav/puppet-autofs#5]
I am getting the following warning when checking the Puppet Style of your module.

```
environments/testing/modules/autofs/manifests/init.pp - WARNING: class inheriting from params class on line 61
Error: styleguide violation in environments/testing/modules/autofs/manifests/init.pp (see above)
Error: 1 styleguide violation(s) found. Commit will be aborted.
Please follow the puppet style guide outlined at:
http://docs.puppetlabs.com/guides/style_guide.html
```

More information: http://puppet-lint.com/checks/class_inherits_from_params_class/

It seems it is unsupported in Puppet 2.6.2 ... 
So not really a big issue, but it would be nice if puppet-lint checks would just work :smile:

**Comment by Yuav** [comment]
That is actually on purpose. Inheriting from params seems to be the new way to organize default parameter values. If you see the the Rakefile, the lint check is actively disabling the error you're seeing;

    # Forsake support for Puppet 2.6.2 for the benefit of cleaner code.
    # http://puppet-lint.com/checks/class_parameter_defaults/
    PuppetLint.configuration.send('disable_class_parameter_defaults')
    # http://puppet-lint.com/checks/class_inherits_from_params_class/
    PuppetLint.configuration.send('disable_class_inherits_from_params_class')

**Comment by aairey** [comment]
Thanks for your explanation.
