### ISSUE TITLE
Directory option for autofs

### ISSUE THREAD

**Issue by kashif74** [Yuav/puppet-autofs#8]
In case of multiple auto.* files, it is helpful to keep all files in a directory. I have forked this module to add option for directory in case of mount_files option.
 I also need to pass some 'options' in case of mount_files. 
My forked version is here
https://github.com/oxford-physics/puppet-autofs 
If it is useful for other people then I can send a pull request

Thanks
Kashif

**Comment by Yuav** [comment]
The options part I definitely want, but the directory part I'm not so sure. Your current implementation is out of sync with mount, and all distros except ArchLinux seems to default to /etc folder (ArchLinux use /etc/autofs, also for auto.master). 

Implementing this I would probably expose it as an option to init.pp as well - and default to a distro specific folder (/etc/autofs on ArchLinux, /etc on everything else) in params. Then use the same default value within the mountfile define.

The current implementation doesn't account for ArchLinux having implemented the /etc/autofs directory, so a directory option should get added to consider this fact anyhow

**Comment by kashif74** [comment]
Hi 
I agree that directory part may not be useful for everyone and it will  clutter the code. It is in our setup because of some historical reason. You  can close this issue.
